name: scheduled-releases

on:
  schedule:
    # Runs every Wednesday at 08:00 UTC (midnight PST / 1:00 AM PDT)
    - cron: '0 8 * * 3'

  # Allows manual triggering for convenience
  workflow_dispatch:

jobs:
  weekly-release:
    runs-on: ubuntu-latest

    env:
      # Declare to satisfy linter, will be set dynamically during workflow execution
      PR_NUMBER: ""
      HAS_NEW_COMMITS: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for new commits
        shell: pwsh
        run: |
          # Check if there are commits between rel/weekly and main
          $commitCount = git rev-list --count rel/weekly..main
          echo "HAS_NEW_COMMITS=$($commitCount -gt 0)" >> $env:GITHUB_ENV

      - name: Create weekly release PR
        if: ${{ env.HAS_NEW_COMMITS == 'true' }}
        shell: pwsh
        run: |
          # Create PR from main to rel/weekly, capture created URL
          $PR_URL = $(gh pr create `
            --base rel/weekly `
            --head main `
            --title "Scheduled weekly release $(Get-Date -Format 'yyyy-MM-dd')" `
            --fill-verbose `
            --reviewer michael-hawker)
          
          # Extract PR number from URL and set as environment variable
          $PR_NUMBER = $($PR_URL | Select-String -Pattern '\d+$').Matches[0].Value
          echo "PR_NUMBER=$PR_NUMBER" >> $env:GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for the PR
        if: ${{ env.HAS_NEW_COMMITS == 'true' }}
        shell: pwsh
        run: |
          gh pr merge ${{ env.PR_NUMBER }} --auto --rebase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
